# Generated by Copilot
import google.generativeai as genai
from agent.state import Product
import json

class EcommerceAgent:
    def __init__(self, api_key: str):
        genai.configure(api_key=api_key)
        
        # Define tools for cart operations
        add_to_cart_tool = genai.protos.Tool(
            function_declarations=[
                genai.protos.FunctionDeclaration(
                    name="add_to_cart",
                    description="Add a product to the shopping cart. Extract just the product type (e.g., 'Shirt', 'Apple') and the color separately.",
                    parameters=genai.protos.Schema(
                        type=genai.protos.Type.OBJECT,
                        properties={
                            "product_name": genai.protos.Schema(type=genai.protos.Type.STRING, description="Name of the product type only (e.g., 'Shirt', 'Apple', 'Phone')"),
                            "color": genai.protos.Schema(type=genai.protos.Type.STRING, description="Color of the product if specified (e.g., 'pink', 'red', 'blue')"),
                            "quantity": genai.protos.Schema(type=genai.protos.Type.INTEGER, description="Quantity to add")
                        },
                        required=["product_name", "quantity"]
                    )
                ),
                genai.protos.FunctionDeclaration(
                    name="remove_from_cart",
                    description="Remove a product completely from the cart or reduce quantity by specified amount",
                    parameters=genai.protos.Schema(
                        type=genai.protos.Type.OBJECT,
                        properties={
                            "product_name": genai.protos.Schema(type=genai.protos.Type.STRING, description="Name of the product to remove"),
                            "quantity": genai.protos.Schema(type=genai.protos.Type.INTEGER, description="Quantity to remove (optional, removes all if not specified)")
                        },
                        required=["product_name"]
                    )
                ),
                genai.protos.FunctionDeclaration(
                    name="update_quantity",
                    description="Update the quantity of a product in the cart",
                    parameters=genai.protos.Schema(
                        type=genai.protos.Type.OBJECT,
                        properties={
                            "product_name": genai.protos.Schema(type=genai.protos.Type.STRING, description="Name of the product"),
                            "new_quantity": genai.protos.Schema(type=genai.protos.Type.INTEGER, description="New quantity")
                        },
                        required=["product_name", "new_quantity"]
                    )
                ),
                genai.protos.FunctionDeclaration(
                    name="clear_cart",
                    description="Clear all items from the shopping cart completely",
                    parameters=genai.protos.Schema(
                        type=genai.protos.Type.OBJECT,
                        properties={},
                        required=[]
                    )
                ),
                genai.protos.FunctionDeclaration(
                    name="get_cart_info",
                    description="Get information about the shopping cart including item count, item names, and details. Use this when user asks questions like 'how many items', 'what's in my cart', 'show cart', 'list items', etc.",
                    parameters=genai.protos.Schema(
                        type=genai.protos.Type.OBJECT,
                        properties={},
                        required=[]
                    )
                )
            ]
        )
        
        # Use gemini-2.5-flash with tools
        self.model = genai.GenerativeModel(
            'models/gemini-2.5-flash',
            tools=[add_to_cart_tool]
        )
        self.chat = self.model.start_chat()
    
    def process_message(self, message: str, state_info: dict):
        try:
            # Build context prompt with strict instructions
            user_name = state_info.get("user_name", "")
            name_instruction = f"The customer's name is {user_name}. Address them by name to make it personal!" if user_name else "If the customer introduces themselves with their name, remember it and use it in future responses!"
            
            context = f"""You are a friendly and knowledgeable e-commerce shopping assistant.

PERSONALITY:
- Be warm, welcoming and enthusiastic about helping customers
- Use emojis to make the conversation friendly and engaging 😊
- Provide helpful product recommendations when customers ask about products
- Sound like a knowledgeable salesperson who loves helping customers find what they need
- {name_instruction}

CAPABILITIES:
1. PRODUCT RECOMMENDATIONS: When customers ask about products (e.g., "show me phones", "what mobiles do you have"), display the catalog in a clean, formatted list
2. CART OPERATIONS: Help add, remove, update quantities, and clear cart
3. CART INFO: Answer questions about cart contents and item counts using get_cart_info function
4. SHOPPING ADVICE: Suggest products, compare items, and help customers make decisions

PRODUCT CATALOG - Display these EXACTLY when asked about products:

📱 MOBILES:
• iPhone 15 Pro
• Samsung Galaxy S24
• Google Pixel 8
• OnePlus 12
• Xiaomi 14

💻 LAPTOPS:
• MacBook Pro M3
• Dell XPS 15
• HP Spectre
• Lenovo ThinkPad
• ASUS ROG

⌚ WATCHES:
• Apple Watch Series 9
• Samsung Galaxy Watch 6
• Garmin Fenix 7
• Fitbit Sense

🎧 HEADPHONES:
• AirPods Pro
• Sony WH-1000XM5
• Bose QC45
• Samsung Buds Pro

📷 CAMERAS:
• Canon EOS R6
• Sony A7 IV
• Nikon Z8
• Fujifilm X-T5

👕 CLOTHING:
• T-Shirt
• Shirt
• Jeans
• Jacket
• Dress
• Sweater
• Shorts

👟 FOOTWEAR:
• Sneakers
• Boots
• Sandals
• Formal Shoes
• Running Shoes

🍎 FRUITS:
• Apple
• Banana
• Orange
• Mango
• Grapes
• Strawberry
• Watermelon

🥕 VEGETABLES:
• Carrot
• Tomato
• Broccoli
• Potato
• Onion
• Cucumber

🍕 FOOD:
• Pizza
• Burger
• Pasta
• Rice
• Noodles
• Sandwich

IMPORTANT RULES:
- When user asks to see products/catalog for a category, display the list EXACTLY as shown above with emojis and bullet points
- If customer says "my name is [name]" or "I'm [name]", remember and use their name in responses
- When user asks "clear cart", use the clear_cart function
- When user asks about cart contents/count, use the get_cart_info function
- When adding items, extract color separately from product name
- Use emojis and formatting to make responses engaging and well-organized!
- Always address customer by name if you know it

Current cart state: {state_info}
"""
            
            full_prompt = f"{context}\n\nUser: {message}"
            response = self.chat.send_message(full_prompt)
            
            actions = []
            bot_message = ""
            
            # Check if model wants to call functions
            if response.candidates[0].content.parts:
                for part in response.candidates[0].content.parts:
                    if hasattr(part, 'function_call') and part.function_call:
                        fc = part.function_call
                        
                        if fc.name == "add_to_cart":
                            product_name = fc.args.get("product_name", "")
                            color = fc.args.get("color", "")
                            quantity = int(fc.args.get("quantity", 1))
                            
                            actions.append({
                                "type": "add_item",
                                "product": Product(
                                    name=product_name,
                                    description=""
                                ),
                                "color": color,
                                "quantity": quantity
                            })
                            
                            if color:
                                bot_message = f"Added {quantity} {color} {product_name}(s) to cart!"
                            else:
                                bot_message = f"Added {quantity} {product_name}(s) to cart!"
                        
                        elif fc.name == "remove_from_cart":
                            qty = fc.args.get("quantity")
                            if qty:
                                actions.append({
                                    "type": "reduce_quantity",
                                    "product_name": fc.args.get("product_name", ""),
                                    "quantity": int(qty)
                                })
                                bot_message = f"Removed {qty} {fc.args.get('product_name')} from cart!"
                            else:
                                actions.append({
                                    "type": "remove_item",
                                    "product_name": fc.args.get("product_name", "")
                                })
                                bot_message = f"Removed {fc.args.get('product_name')} from cart!"
                        
                        elif fc.name == "update_quantity":
                            actions.append({
                                "type": "update_quantity",
                                "product_name": fc.args.get("product_name", ""),
                                "quantity": int(fc.args.get("new_quantity", 1))
                            })
                            bot_message = f"Updated {fc.args.get('product_name')} quantity to {fc.args.get('new_quantity')}!"
                        
                        elif fc.name == "clear_cart":
                            actions.append({
                                "type": "clear_cart"
                            })
                            bot_message = "Cart cleared! All items have been removed."
                        
                        elif fc.name == "get_cart_info":
                            # Get current cart info
                            cart_items = state_info.get("cart", [])
                            total_items = sum(qty for _, qty, _ in cart_items)
                            
                            if total_items == 0:
                                bot_message = "Your cart is empty. Would you like to add some items?"
                            else:
                                items_list = ", ".join([f"{name} (x{qty})" for name, qty, _ in cart_items])
                                bot_message = f"You have {total_items} item(s) in your cart: {items_list}"
                    
                    elif hasattr(part, 'text') and part.text:
                        bot_message = part.text
            
            # Check if user is introducing themselves (extract name)
            import re
            name_patterns = [
                r"(?:my name is|i'm|i am|this is|call me)\s+([A-Z][a-z]+)",
                r"^([A-Z][a-z]+)(?:\s+here|$)",
            ]
            
            detected_name = None
            for pattern in name_patterns:
                match = re.search(pattern, message, re.IGNORECASE)
                if match:
                    detected_name = match.group(1).capitalize()
                    # Add action to save the name
                    actions.append({
                        "type": "save_name",
                        "name": detected_name
                    })
                    break
            
            if not bot_message:
                bot_message = "Hello! I'm your shopping assistant. How can I help you today? You can add items to your cart, update quantities, or remove items!"
            
            return {
                "message": bot_message,
                "actions": actions
            }
            
        except Exception as e:
            return {
                "message": f"Error: {str(e)}",
                "actions": []
            }
