# Generated by Copilot
from dataclasses import dataclass
from typing import List, Tuple, Dict

@dataclass
class Product:
    name: str
    price: float = 0.0
    color: str = ""
    description: str = ""

class ShoppingState:
    def __init__(self):
        self.cart: Dict[str, Tuple[Product, int]] = {}
        self.messages: List[Dict[str, str]] = []
        self.user_name: str = ""
    
    def add_to_cart(self, product: Product, quantity: int = 1, color: str = ""):
        # Update product color if provided
        if color:
            product.color = color
        
        if product.name in self.cart:
            _, existing_qty = self.cart[product.name]
            self.cart[product.name] = (product, existing_qty + quantity)
        else:
            self.cart[product.name] = (product, quantity)
    
    def remove_from_cart(self, product_name: str):
        if product_name in self.cart:
            del self.cart[product_name]
    
    def update_quantity(self, product_name: str, quantity: int):
        if product_name in self.cart:
            product, _ = self.cart[product_name]
            self.cart[product_name] = (product, quantity)
    
    def reduce_quantity(self, product_name: str, quantity: int):
        if product_name in self.cart:
            product, current_qty = self.cart[product_name]
            new_qty = current_qty - quantity
            if new_qty <= 0:
                del self.cart[product_name]
            else:
                self.cart[product_name] = (product, new_qty)
    
    def clear_cart(self):
        self.cart.clear()
    
    def get_cart_items(self) -> List[Tuple[Product, int]]:
        return list(self.cart.values())
    
    def add_message(self, role: str, content: str):
        self.messages.append({"role": role, "content": content})
    
    def set_user_name(self, name: str):
        self.user_name = name
    
    def get_user_name(self) -> str:
        return self.user_name
    
    def get_state_info(self) -> Dict:
        return {
            "cart": [(p.name, qty, p.price) for p, qty in self.cart.values()],
            "total": sum(p.price * qty for p, qty in self.cart.values()),
            "user_name": self.user_name
        }
